{%- if CODEJAIL_ENABLE_HPA %}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: codejail-hpa
  labels:
    app.kubernetes.io/name: codejail-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: codejailservice
  minReplicas: {{ CODEJAIL_MIN_REPLICAS }}
  maxReplicas: {{ CODEJAIL_MAX_REPLICAS }}
  metrics:
  {%- if CODEJAIL_AVG_CPU > 0 %}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ CODEJAIL_AVG_CPU }}
  {%- endif %}
  {%- if CODEJAIL_AVG_MEMORY|length %}
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ CODEJAIL_AVG_MEMORY }}
  {%- endif %}
{%- endif %}
