{%- if CODEJAIL_ENABLE_HPA %}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: codejail
  labels:
    app.kubernetes.io/name: codejail
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: codejailservice
  minReplicas: {{ CODEJAIL_MIN_REPLICAS }}
  maxReplicas: {{ CODEJAIL_MAX_REPLICAS }}
  {%- if CODEJAIL_AVG_CPU > 0 %}
  targetCPUUtilizationPercentage: {{ CODEJAIL_AVG_CPU }}
  {%- endif %}
{%- endif %}
