name: Unit tests, QA

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - main
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
         python-version: ['3.9', '3.12']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: requirements/dev.txt
    - name: Install dependencies
      run: |
        make requirements
    - name: Run the QA suite
      run: |
        make quality
